# Generated by Django 5.1.6 on 2025-02-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_listened_alter_album_artist_alter_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='listened',
            field=models.BigIntegerField(default=0),
        ),
    ]
